@Interlink.Test_HostAddress = https://localhost:7219

GET {{Interlink.Test_HostAddress}}/api/pet/
Accept: application/json

###

POST {{Interlink.Test_HostAddress}}/api/pet
Content-Type: application/json

{
  "name": "Azragg",
  "species": "dog"
}

###

PUT {{Interlink.Test_HostAddress}}/api/pet
Content-Type: application/json

{
  "id": 4,
  "name": "Azrag",
  "species": "dog"
}

###

@id=5
DELETE {{Interlink.Test_HostAddress}}/api/pet/{{id}}

###
