<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<RootNamespace>Interlink.Analyzers</RootNamespace>
		<AssemblyName>Interlink.Analyzers</AssemblyName>
		<PackageId>Interlink.Analyzers</PackageId>
		<Version>1.5.1</Version>
		<Description>Roslyn analyzer that detects requests without corresponding handlers for the Interlink mediator library.</Description>
		<Authors>Manojbabu</Authors>
		<PackageTags>interlink mediator analyzer roslyn cqrs</PackageTags>
		<PackageProjectUrl>https://github.com/manusoft/Interlink-cqrs-library</PackageProjectUrl>
		<RepositoryUrl>https://github.com/manusoft/Interlink-cqrs-library</RepositoryUrl>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<IsPackable>true</IsPackable>
		<DevelopmentDependency>true</DevelopmentDependency>
		<SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="icon.png" Pack="true" PackagePath="" Condition="Exists('icon.png')"/>
		<Content Include="README.md" Pack="true" PackagePath="" Condition="Exists('README.md')"/>
		<Content Include="LICENSE.txt" Pack="true" PackagePath="" Condition="Exists('LICENSE.txt')"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

</Project>
